### ISSUE TITLE
64-bit Update?

### ISSUE THREAD

**Issue by jeffgrann** [miyako/4d-plugin-process-information#2]
Are you planning to update this plugin for 4D v16 64-bit?

**Comment by miyako** [comment]
which commands are you using? 
I didn't expect the plugin to have practical value except for the part that has been branched

**Comment by jeffgrann** [comment]
Just BEGIN IMPORTANT ACTIVITY, but I assume this is no longer necessary.

**Comment by miyako** [comment]
4D is already compatible with App Nap (in a standard way), but if you feel you need the command, I could make it 64-bit.

**Comment by jeffgrann** [comment]
If that is the case, then I no longer need this plugin. Thank you again.
